# Generated by Django 6.1 on 2026-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills/tags', max_length=255, null=True),
        ),
    ]
