# Generated by Django 6.1 on 2026-09-13 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_str', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('date_range', models.CharField(max_length=100)),
                ('description_header', models.CharField(default='Coursework:', max_length=255)),
                ('coursework', models.TextField(help_text='Newline-separated list of courses')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
