# Generated by Django 6.1 on 2026-09-16 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_competition_education_experience_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_str',
            field=models.CharField(help_text="Display date string like 'Jul 2024' or '2026'", max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. Debate, Public Speaking, Academic)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
