# Generated by Django 6.1 on 2026-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_alter_competition_date_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organization', 'Organization'), ('leadership', 'Leadership')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.CharField(blank=True, help_text="Display duration like '2023 – Present' or 'Jul 2023 – Aug 2024'", max_length=100, null=True),
        ),
    ]
