# Generated by Django 6.1 on 2026-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_category_alter_experience_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='ended_at',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Internship, Volunteer, Organization', max_length=255, null=True),
        ),
    ]
